# ios_rules_registry.py

def get_ios_assisted_rules():
    return [
        {
            "id": "ios-missing-label",
            "name": "Controls must have accessible labels",
            "wcag": "1.1.1",
            "level": "A",
            "severity": "critical",
            "test_type": "assisted",
            "automation_assist": "Identify interactive elements visually.",
            "manual_remaining": "Enable VoiceOver and verify each control is announced meaningfully.",
            "status": "not_tested",
        },
        {
            "id": "ios-focus-order",
            "name": "Focus order must be logical",
            "wcag": "2.4.3",
            "level": "A",
            "severity": "serious",
            "test_type": "assisted",
            "automation_assist": "Ensure elements exist in a logical sequence.",
            "manual_remaining": "Swipe left/right with VoiceOver and confirm logical order.",
            "status": "not_tested",
        },
        {
            "id": "ios-focus-visible",
            "name": "Focus must be visible",
            "wcag": "2.4.7",
            "level": "AA",
            "severity": "serious",
            "test_type": "assisted",
            "automation_assist": "Check focusable elements.",
            "manual_remaining": "Confirm focused element is visually highlighted.",
            "status": "not_tested",
        },
        {
            "id": "ios-touch-target",
            "name": "Touch targets must be large enough",
            "wcag": "2.5.8",
            "level": "AA",
            "severity": "serious",
            "test_type": "manual",
            "manual_remaining": "Verify touch targets are at least 44x44pt.",
            "status": "not_tested",
        },
        {
            "id": "ios-gesture-alternative",
            "name": "Complex gestures must have alternatives",
            "wcag": "2.5.1",
            "level": "A",
            "severity": "critical",
            "test_type": "manual",
            "manual_remaining": "Verify all multi-finger or custom gestures have alternatives.",
            "status": "not_tested",
        },
        {
            "id": "ios-error-announcement",
            "name": "Errors must be announced",
            "wcag": "3.3.1",
            "level": "A",
            "severity": "serious",
            "test_type": "assisted",
            "automation_assist": "Trigger an error condition.",
            "manual_remaining": "Confirm VoiceOver announces the error clearly.",
            "status": "not_tested",
        },
        {
            "id": "ios-dynamic-updates",
            "name": "Dynamic updates must be announced",
            "wcag": "4.1.3",
            "level": "AA",
            "severity": "serious",
            "test_type": "assisted",
            "automation_assist": "Observe dynamic UI changes.",
            "manual_remaining": "Confirm VoiceOver announces content updates.",
            "status": "not_tested",
        },
        {
            "id": "ios-cognitive-load",
            "name": "Instructions must be clear and consistent",
            "wcag": "3.3.2",
            "level": "AA",
            "severity": "moderate",
            "test_type": "manual",
            "manual_remaining": "Evaluate clarity and consistency of instructions.",
            "status": "not_tested",
        },
    ]
